/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'name' : string, 'items' : Array<MenuItem> }
export interface MenuItem {
  'name' : string,
  'note' : [] | [string],
  'price' : bigint,
}
export interface Order {
  'customerName' : string,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'discountPercent' : bigint,
  'orderId' : bigint,
  'customerAddress' : string,
  'totalAmount' : bigint,
  'dateString' : string,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface OrderItem {
  'itemName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type PaymentMethod = { 'cod' : null } |
  { 'upi' : null };
export interface _SERVICE {
  'addOrder' : ActorMethod<
    [
      string,
      string,
      string,
      Array<OrderItem>,
      bigint,
      bigint,
      PaymentMethod,
      string,
    ],
    bigint
  >,
  'getDiscount' : ActorMethod<[], bigint>,
  'getMenu' : ActorMethod<[], Array<Category>>,
  'getOnlineStatus' : ActorMethod<[], boolean>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByDate' : ActorMethod<[string], Array<Order>>,
  'getTotalByDate' : ActorMethod<[string], bigint>,
  'setDiscount' : ActorMethod<[bigint], undefined>,
  'setOnlineStatus' : ActorMethod<[boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
