/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const Category = IDL.Record({
  'name' : IDL.Text,
  'items' : IDL.Vec(MenuItem),
});

export const idlService = IDL.Service({
  'getMenu' : IDL.Func([], [IDL.Vec(Category)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const Category = IDL.Record({
    'name' : IDL.Text,
    'items' : IDL.Vec(MenuItem),
  });
  
  return IDL.Service({
    'getMenu' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };